// Generated by CoffeeScript 1.9.0
var app;

app = angular.module('myApp.viewRiotResume', ['ngRoute', 'myApp.skrollr']);

app.config([
  '$routeProvider', function($routeProvider) {
    return $routeProvider.when('/riotresume', {
      templateUrl: 'viewRiotResume/riotResume.html',
      controller: 'riotResumeCtrl'
    });
  }
]);

app.controller('riotResumeCtrl', [
  '$scope', function($scope) {
    $scope.hideNavBar = true;
    return skrollr.init();
  }
]);
