// Generated by CoffeeScript 1.9.0
describe('myApp.viewRiotResume', function() {
  return describe('riotResumeCtrl', function() {
    return it('should be a resume or somesuch', function() {
      return expect(true).toEqual(true);
    });
  });
});
