// Generated by CoffeeScript 1.9.0
var app;

app = angular.module('myApp.viewCommunity', ['ngRoute']);

app.config([
  '$routeProvider', function($routeProvider) {
    return $routeProvider.when('/community', {
      templateUrl: 'viewCommunity/community.html',
      controller: 'communityCtrl'
    });
  }
]);

app.controller('communityCtrl', [
  '$scope', function($scope) {
    return $scope.potato = "potato";
  }
]);
