// Generated by CoffeeScript 1.9.0
'use strict';
var NavBarCtrl;

angular.module('myApp', ['ngRoute', 'myApp.viewHome', 'myApp.viewResume', 'myApp.viewRiotResume', 'myApp.viewCommunity', 'myApp.viewBlog', 'myApp.viewStream', 'myApp.view1', 'myApp.view2', 'myApp.version']).config([
  '$routeProvider', function($routeProvider) {
    return $routeProvider.otherwise({
      redirectTo: '/home'
    });
  }
]);

NavBarCtrl = function($scope, $location) {
  $scope.isCollapsed = true;
  return $scope.isActivePath = function(viewLocation) {
    return viewLocation === $location.path();
  };
};
