// Generated by CoffeeScript 1.9.0
angular.module('myApp.skrollr', []).directive('skrollrTag', function() {
  var directiveDefinitionObject;
  return directiveDefinitionObject = {
    link: function() {
      skrollr.get().refresh();
      return null;
    }
  };
});
