// Generated by CoffeeScript 1.9.0
var app;

app = angular.module('myApp.viewHome', ['ui.bootstrap', 'ngRoute']);

app.config([
  '$routeProvider', function($routeProvider) {
    return $routeProvider.when('/home', {
      templateUrl: 'viewHome/home.html',
      controller: 'homeCtrl'
    });
  }
]);

app.controller('homeCtrl', [
  '$scope', function($scope) {
    return $scope.potato = "potato";
  }
]);
