// Generated by CoffeeScript 1.9.0
var app;

app = angular.module('myApp.viewResume', ['ui.bootstrap', 'ngRoute']);

app.config([
  '$routeProvider', function($routeProvider) {
    return $routeProvider.when('/viewResume', {
      templateUrl: 'viewResume/resume.html',
      controller: 'resumeCtrl'
    });
  }
]);

app.controller('resumeCtrl', [
  '$scope', function($scope) {
    return $scope.potato = "potato";
  }
]);
