// Generated by CoffeeScript 1.9.0
describe('myApp.viewBlog', function() {
  return describe('blogCtrl', function() {
    return it('should things', function() {
      return expect(true).toEqual(true);
    });
  });
});
